### ISSUE TITLE
$HOME environment variable is required for .netrc detection in tests

### ISSUE THREAD

**Issue by chrisirhc** [theoremlp/rules_uv#103]
Found this out as I was investigating why the authentication wouldn't work only on the test of the pip_compile.
Creating an issue in case it would be helpful to another person. To add it, add `--test_env=HOME` such as in `.bazelrc`. 

It might be worth adding this to the README in case someone else hits this issue.

Related ticket https://github.com/gribouille/netrc/issues/4 .

**Comment by chrisirhc** [comment]
Hmn curious why not add a note to readme on this?

**Comment by mark-thm** [comment]
Ah, sorry, I meant to leave a message when I closed this -- this seems like something not particular to this ruleset but more general w/r/t how Bazel and .netrc interact. Open to adding a line to the README, seemed like an odd place, though, and your issue captures the thing to do.

**Comment by chrisirhc** [comment]
Ah I didn’t mention that this can be confusing to users who are coming from pip since pip has a workaround that detects .netrc without the $HOME variable.

**Comment by chrisirhc** [comment]
Found a clean way to inherit $HOME, created a PR.
