### ISSUE TITLE
output of uv pip compile has wrong syntax with extras

### ISSUE THREAD

**Issue by alexeagle** [theoremlp/rules_uv#110]
This may be a bug in `uv`, I'm not sure how to tell and haven't had time to dig in. Please forgive me filing an issue that's not well-researched :)

Installing a package with extras, such as `etils[epath, epy]` results in output from the `pip_compile` rule which has some whitespace issue.

Here's the patch one of my clients applied to workaround it:

```diff
diff --git a/uv/private/pip_compile.sh b/uv/private/pip_compile.sh
index 63b8a6d..260c31e 100644
--- a/uv/private/pip_compile.sh
+++ b/uv/private/pip_compile.sh
@@ -8,6 +8,16 @@ REQUIREMENTS_TXT="{{requirements_txt}}"

 {{uv}} pip compile \
     {{args}} \
-    --output-file="$REQUIREMENTS_TXT" \
     "$REQUIREMENTS_IN" \
-    "$@"
+    "$@" | \
+awk '{
+    if (match($0, /\[[^]]+\]/)) {
+        before = substr($0, 1, RSTART-1)
+        bracket_content = substr($0, RSTART+1, RLENGTH-2)
+        after = substr($0, RSTART+RLENGTH)
+        gsub(/[[:space:]]*,[[:space:]]*/, ",", bracket_content)
+        print before "[" bracket_content "]" after
+    } else {
+        print $0
+    }
+}' | tee "$REQUIREMENTS_TXT"
\ No newline at end of file
```

**Comment by mark-thm** [comment]
If you need to overwrite requirements.txt it's a uv bug, I believe.

**Comment by alexeagle** [comment]
sorry to continue conversation in rules_uv when I agree it's not your bug 😁 

Interesting - @s0h3yl  I tracked down the spot: https://github.com/pypa/packaging/blob/23.1/src/packaging/_parser.py#L199
it's clear that the grammar here should permit whitespace, and the tokenizer is told to consume "WS" but for 

`transformers[sentencepiece, torch]==4.35.2 `

I get
```
  File "/home/alex/.cache/bazel/_bazel_alex/c18c578b4ecea221790803eee605d790/sandbox/linux-sandbox/37/execroot/assemblyai/bazel-out/k8-opt-exec-ST-13d3ddad9198/bin/external/rules_python/tools/wheelmaker.runfiles/pypi__packaging/packaging/requirements.py", line 37, in __init__
    raise InvalidRequirement(str(e)) from e
packaging.requirements.InvalidRequirement: Expected extra name after comma
    transformers[sentencepiece,
```

while it is happy with `transformers[sentencepiece,torch]==4.35.2 ` (whitespace removed)

**Comment by alexeagle** [comment]
Filed https://github.com/astral-sh/uv/issues/7520
