### ISSUE TITLE
UV rules integration with python toolchain

### ISSUE THREAD

**Issue by Andreii20** [theoremlp/rules_uv#142]
Hi,

Could you please help with a little more information about uv_rules integration with python toolchains?
Wasn't able to find information about it aside from a small example under bzlmod here:
[https://github.com/bazelbuild/rules_python/blob/main/examples/bzlmod/MODULE.bazel](https://github.com/bazelbuild/rules_python/blob/main/examples/bzlmod/MODULE.bazel)

```
# EXPERIMENTAL: This is experimental and may be removed without notice
uv = use_extension("@rules_python//python/uv:extensions.bzl", "uv")
uv.toolchain(uv_version = "0.2.23")
use_repo(uv, "uv_toolchains")

register_toolchains("@uv_toolchains//:all")
```

Could you please explain how this is working and how it should behave? And could you please explain how to use/load a dep from the venv within a binary for instance while making use of the python interpreter defined in the toolchain, not the system one.

Huge thanks in advance! 

Kind regards,
Andrei

**Comment by mark-thm** [comment]
You’ve linked to work the rules_python authors are doing to incorporate uv into rules_python. rules_uv is entirely distinct from that work and has a very narrow scope:
1. Resolve requirements.in files to requirements.txt files, predominantly as an alternative to rules_python’s compile_pip_dependencies macro
2. Make it easy to construct a venv containing the dependencies from requirements.txt files for use in local development

rules_uv does not aim to make a toolchain or uv binaries available for other use. It also does not aim to change how one uses a dependency from rules_python. Please see rules_python’s docs for how to use a requirements.txt file and to depend on requirements in py_library, py_test, and py_binary targets.
