### ISSUE TITLE
Mark some bazel deps as dev dependencies

### ISSUE THREAD

**Issue by aaronsky** [theoremlp/rules_uv#149]
Hi – thank you for making this. I wanted to see if some of the bazel deps you have declared in the `MODULE.bazel` can be marked as dev dependencies. I think it might just be buildifier, but I thought I'd ask.

**Comment by mark-thm** [comment]
multitool is a requirement (it's how this ruleset gets uv).

Because of the way BCR works it seems like buildifier_prebuilt needs to be declared as a regular dependency rather than a dev dependency (originally I had it as a dev dependency).
