### ISSUE TITLE
Adding `pyproject.toml` overrides break tests

### ISSUE THREAD

**Issue by ewhauser** [theoremlp/rules_uv#155]
We've had to add an override in our workspace for protobuf via `pyproject.toml`:

```
[tool.uv]
override-dependencies = [
  "protobuf == 5.28.2",
]
```

We expect this file in our main `BUILD.bazel`:

```bazel
 exports_files([
     "pyproject.toml",
 ])
```

The requirements file updates fine with the correct override, however, the test does not pick it up and it fails.

**Comment by mark-thm** [comment]
You need to include this file in the data arg:

```
pip_compile(
    …
    data = [“//:pyproject.toml”]
    …
)
```

**Comment by ewhauser** [comment]
Got it - thanks!
