### ISSUE TITLE
auto-release to registry.bazel.build

### ISSUE THREAD

**Issue by jab** [theoremlp/rules_uv#69]
According to https://github.com/theoremlp/rules_uv/releases/tag/v0.15.0 a new GitHub release was published 6 hours ago, a corresponding tag was [published by one autorelease job](https://github.com/theoremlp/rules_uv/actions/runs/9632906620/job/26566669882), but the [latest release published to registry.bazel.build](https://registry.bazel.build/modules/rules_uv) is still 0.14.0. Please use this issue to track publishing 0.15.0 to the registry as well as automating that for future releases, if you like.

<img width="2053" alt="Screenshot 2024-06-23 at 1 07 02 PM" src="https://github.com/theoremlp/rules_uv/assets/64992/09b62d2d-8557-4a7e-b437-095e36bf3f59">

**Comment by mark-thm** [comment]
The registry itself requires registry maintainers — https://github.com/bazelbuild/bazel-central-registry/pull/2306 is waiting on their review.

**Comment by jab** [comment]
Didn't realize, sorry for the noise and thanks for the link! Just subscribed to that PR to find out when it's approved.
