### ISSUE TITLE
pip_compile fails on buildbarn RBE

### ISSUE THREAD

**Issue by jsharpe** [theoremlp/rules_uv#91]
Buildbarn RBE makes the inputs read-only - it looks like rules_uv is trying to write to the input files when running the diff_test.
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //python:deps_diff_test
-----------------------------------------------------------------------------
error: failed to create file `__updated__`
  Caused by: Permission denied (os error 13)
```

Adding tags=["no-remote"] allows this test to complete so its an issue with the permissions on the input files.

**Comment by mark-thm** [comment]
The test creates a new file called `__updated__` -- I'm not familiar with buildbarn RBE and don't really have a way to debug this, but the test _needs_ to be able to make a new file.
