### ISSUE TITLE
Unbound variable when creating a venv

### ISSUE THREAD

**Issue by hentt30** [theoremlp/rules_uv#92]
For rules_uv >= 0.18.0, the create_venv.sh script fails with the error `"bash site_packages_extra_files[@]: unbound variable"` when site_packages_extra_files is not set. The root cause appears to be the -u option in set -u, which interprets ${site_packages_extra_files[@]} as unset.

How to reproduce: 
`docker run -it --entrypoint bash bash:3.2.57 -c 'set -euo pipefail; for file in "${site_packages_extra_files[@]}"; do echo "test"; done;'`

Solution:
check whether the variable `site_packages_extra_files` exists before executing the for loop.

**Comment by mark-thm** [comment]
Fixed by https://github.com/theoremlp/rules_uv/commit/531938b24f3ab5ba0bb97a991ec01acedf1d20e3

**Comment by hentt30** [comment]
Tks!
