### ISSUE TITLE
Easier migration from rules_python pip_compile: test and update targets

### ISSUE THREAD

**Issue by alexeagle** [theoremlp/rules_uv#96]
The `compile_pip_requirements` macro in rules_python produces a `[name]_test` target to verify that requirements are up-to-date, and a runnable `[name].update` target to perform the update.
 
https://github.com/bazelbuild/rules_python/blob/fa13b0138924245c55f79922509e4688f252ff71/python/private/pypi/pip_compile.bzl#L46-L49

It's an extra burden for users migrating from that rule to account for the loss of these two targets when adding rules_uv.

**Comment by mark-thm** [comment]
I'm open to aliases that match the rules_python names.

**Comment by alexeagle** [comment]
Are you open to a breaking change where we just change `[name]_diff_test` to `[name]_test` to match rules_python? This variance seems accidental.

For updating, I suppose there's no harm allowing both `bazel run [name]` and `bazel run [name].update` - I went with the latter in rules_python due to the "custom verb" pattern as documented on https://bazel.build/rules/verbs-tutorial

**Comment by mark-thm** [comment]
I don't mind the test name change but would prefer an alias on the run target over a breaking change, as it'll cause a break on automation I have to go personally fix :)

**Comment by mark-thm** [comment]
fwiw, we intended the test to be called `_diff_test` in line with `write_source_files`' naming convention (it is, after all, a diff test)

**Comment by alexeagle** [comment]
I don't think that's how we named it either:

https://docs.aspect.build/rulesets/aspect_bazel_lib/docs/write_source_files

>By default, a diff_test target ("{name}_test")
